Add Support for `std::string_view`
pajlada/serialize pull request #9
Opened 2023-04-06 19:28 UTC by Nerixyz

This PR adds support for serializing and deserializing [`std::string_view`](https://en.cppreference.com/w/cpp/string/basic_string_view). This is useful when doing zero-copy (de-)serialization.

2023-04-06 19:42 UTC, Nerixyz commented
Note: https://github.com/Tencent/rapidjson/issues/836#issuecomment-277642411 mentioned a problem for empty string-views and using `GenericStringRef`. Rapidjson [checks the pointer at construction now](https://github.com/Tencent/rapidjson/blob/083f359f5c36198accc2b9360ce1e32a333231d9/include/rapidjson/document.h#L412), so this shouldn't be an issue ([added in July 2017](https://github.com/Tencent/rapidjson/commit/47c3c1ec9f5c3724c5befb42f8323e760acc1f69)).

2023-04-07 07:07 UTC, pajlada requested changes
We don't vendor RapidJSON, and OS distributions are behind since RapidJSON has been slow with stable releases.
Add tests for default-constructible/"null" string views and you'll see it fails in CI

2023-04-07 11:08 UTC, pajlada approved these changes

2023-04-07 11:08 UTC, pajlada commented
Thank you for your contribution!

2023-04-07 11:09 UTC, merged